---
platform: linux

inputs:
  - name: src
  - name: docker-cache/app-prebuilt
  # - name: docker-cache/<% image name %>-image

params:
  ON_CONCOURSE: true

run:
  path: src/ci/tasks/scripts/test.sh
